language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: $organizationName
    token:
      secure: $token

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
#  - cobertura:cobertura

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


after_success:
  - bash <(curl -s https://codecov.io/bash)